# verison
# services to start
    # servicename
      # container_name
      # image and its version
      # restart props to make it run when container fails
      # volumes a folder to save database files and give the path name
    # node js api service uses Dockerfile

version: '3.9'

services:
   #MongoDB service
    mongo_db:
      container_name: db_container
      image: mongo:latest
      restart: always
      ports:
        - 2717:27017    #to map port
      volumes: 
        - mongo_db:/data/db
  # Node js API service
    api:
      build: .
      ports:
        - 5000:3000
      volumes:
        - .:/usr/src/app
      environment: 
        PORT: 3000
        MONGODB_URI: mongodb://mongo_db:27017/DockerTest
      depends_on:
        - mongo_db

volumes:
  mongo_db: {}
